
---
# yaml plugin used

all: 
  hosts: 
    f5-bigip-1:
      ansible_host: 172.16.1.201
    webserver-1:
      ansible_host: 172.16.1.200
      hostname: webserver-1
    webserver-2:
      ansible_host: 172.16.1.199
      hostname: webserver-2
  children:
    f5:
      hosts:
        f5-bigip-1:
    linux: 
      hosts: 
        webserver-1:
        webserver-2:
    function_webserver:
      hosts: 
        webserver-1:
        webserver-2: